version: "3"

services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server
    container_name: mssqldb
    environment:
      MSSQL_SA_PASSWORD: "Waek3aig9oovu9upheih1mo3z"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./mssqldata:/var/opt/mssql    
 